### ISSUE TITLE
load_project error

### ISSUE THREAD

**Issue by longlong-zhang** [OpenGeoVis/omfvista#10]
Hello all,
  I met an error when i tried to use this module,and i have attached my error message in this submit.
  Hopping for any suggestions to help me tackle this problem.
![omftovtk](https://user-images.githubusercontent.com/50805242/80855986-a9be3300-8c78-11ea-8978-0cb9726aa5c1.png)

**Comment by banesullivan** [comment]
You simply need to change your script's file name as it is called `omf.py` which is the same as the [`omf` Python package](https://omf.readthedocs.io/en/latest/) you are using under the hood. That script you have has a higher priority in your path so things aren't getting imported correctly and this error message is just a red herring 


Apologies for the delay....
